"""
Pure formatting step, no network: reads games_data.json and writes the
three committed data files under ../data/. Safe to re-run any time the JS
schema needs a tweak, without re-hitting the MLB Stats API.

Usage: python3 render_js.py
"""
import json
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, '..', 'data')
CACHE_PATH = os.path.join(SCRIPT_DIR, 'games_data.json')


def js_literal(value):
    return json.dumps(value, indent=2)


def main():
    with open(CACHE_PATH) as f:
        games = json.load(f)

    # gameDate (exact UTC start time) is the real tiebreaker for same-day
    # games -- a doubleheader plus an unrelated third game at a different
    # park don't otherwise have a stable chronological order (gamePk
    # isn't sequential by start time). Falls back to gamePk for any
    # older record somehow still missing it.
    games.sort(key=lambda g: (g['date'], g.get('gameDate') or '', g.get('gamePk', 0)))

    # ---- games.js: lean, drives the game list + overview stats ----
    lean = [
        {
            "gamePk": g['gamePk'],
            "date": g['date'],
            "gameDate": g.get('gameDate'),
            "homeTeam": g['homeTeam'],
            "awayTeam": g['awayTeam'],
            "homeScore": g['homeScore'],
            "awayScore": g['awayScore'],
            "venue": g['venue'],
            "gameType": g['gameType'],
            "notes": g['notes'],
            "attendedBy": g['attendedBy'],
        }
        for g in games
    ]
    games_js = (
        "/* Every MLB game the family has personally attended, one row per\n"
        "   game, sorted chronologically ascending. Regenerated by\n"
        "   scripts/render_js.py from scripts/games_data.json -- do not\n"
        "   hand-edit this file; add new games to scripts/games_raw.py and\n"
        "   re-run the pipeline (fetch_games.py then render_js.py) instead. */\n"
        f"var mlbGames = {js_literal(lean)};\n"
    )
    with open(os.path.join(DATA_DIR, 'games.js'), 'w') as f:
        f.write(games_js)

    # ---- games-detail.js: box score / weather / decisions / linescore layer ----
    detail = {}
    for g in games:
        detail[str(g['gamePk'])] = {
            "status": g['status'],
            "statusReason": g['statusReason'],
            "homeHits": g['homeHits'],
            "awayHits": g['awayHits'],
            "homeHR": g['homeHR'],
            "awayHR": g['awayHR'],
            "homeDoubles": g['homeDoubles'],
            "awayDoubles": g['awayDoubles'],
            "homeTriples": g['homeTriples'],
            "awayTriples": g['awayTriples'],
            "homeStrikeouts": g['homeStrikeouts'],
            "awayStrikeouts": g['awayStrikeouts'],
            "homeWalks": g['homeWalks'],
            "awayWalks": g['awayWalks'],
            "homeAtBats": g.get('homeAtBats'),
            "awayAtBats": g.get('awayAtBats'),
            "homePlateAppearances": g.get('homePlateAppearances'),
            "awayPlateAppearances": g.get('awayPlateAppearances'),
            "homeStolenBases": g.get('homeStolenBases'),
            "awayStolenBases": g.get('awayStolenBases'),
            "homeCaughtStealing": g.get('homeCaughtStealing'),
            "awayCaughtStealing": g.get('awayCaughtStealing'),
            "homeHitByPitch": g.get('homeHitByPitch'),
            "awayHitByPitch": g.get('awayHitByPitch'),
            "homeSacBunts": g.get('homeSacBunts'),
            "awaySacBunts": g.get('awaySacBunts'),
            "homeSacFlies": g.get('homeSacFlies'),
            "awaySacFlies": g.get('awaySacFlies'),
            "homeLeftOnBase": g.get('homeLeftOnBase'),
            "awayLeftOnBase": g.get('awayLeftOnBase'),
            "homeGroundIntoDoublePlay": g.get('homeGroundIntoDoublePlay'),
            "awayGroundIntoDoublePlay": g.get('awayGroundIntoDoublePlay'),
            "homeRbi": g.get('homeRbi'),
            "awayRbi": g.get('awayRbi'),
            "homeTotalBases": g.get('homeTotalBases'),
            "awayTotalBases": g.get('awayTotalBases'),
            "homePitchStrikeouts": g.get('homePitchStrikeouts'),
            "awayPitchStrikeouts": g.get('awayPitchStrikeouts'),
            "homePitchWalks": g.get('homePitchWalks'),
            "awayPitchWalks": g.get('awayPitchWalks'),
            "homeEarnedRuns": g.get('homeEarnedRuns'),
            "awayEarnedRuns": g.get('awayEarnedRuns'),
            "homeNumberOfPitches": g.get('homeNumberOfPitches'),
            "awayNumberOfPitches": g.get('awayNumberOfPitches'),
            "homeWildPitches": g.get('homeWildPitches'),
            "awayWildPitches": g.get('awayWildPitches'),
            "homeBalks": g.get('homeBalks'),
            "awayBalks": g.get('awayBalks'),
            "homeHitBatsmen": g.get('homeHitBatsmen'),
            "awayHitBatsmen": g.get('awayHitBatsmen'),
            "homeErrors": g.get('homeErrors'),
            "awayErrors": g.get('awayErrors'),
            "homeAssists": g.get('homeAssists'),
            "awayAssists": g.get('awayAssists'),
            "homePutOuts": g.get('homePutOuts'),
            "awayPutOuts": g.get('awayPutOuts'),
            "winPitcher": g['winPitcher'],
            "lossPitcher": g['lossPitcher'],
            "savePitcher": g['savePitcher'],
            "weather": g['weather'],
            "crowdSize": g['crowdSize'],
            "duration": g['duration'],
            "dayNight": g['dayNight'],
            "doubleheader": g['doubleheader'],
            "extraInnings": g['extraInnings'],
            "inningsPlayed": g['inningsPlayed'],
            "innings": g['innings'],
            "cycles": g['cycles'],
        }
    detail_js = (
        "/* Box-score/weather/decisions/linescore layer, keyed by gamePk\n"
        "   (as a string -- JS object keys are always strings). Regenerated\n"
        "   by scripts/render_js.py -- do not hand-edit. */\n"
        f"var mlbGameDetail = {js_literal(detail)};\n"
    )
    with open(os.path.join(DATA_DIR, 'games-detail.js'), 'w') as f:
        f.write(detail_js)

    # ---- games-players.js: dedup'd player lookup + per-game appearance lists ----
    players = {}
    game_players = {}
    for g in games:
        appearances = []
        for p in g['players']:
            players[str(p['id'])] = p['name']
            appearances.append({"id": p['id'], "team": p['team'], "position": p.get('position'), "gamesStarted": p.get('gamesStarted')})
        game_players[str(g['gamePk'])] = appearances

    players_js = (
        "/* id -> full name, deduped across every game so a player who\n"
        "   recurs across many attended games (e.g. a long-tenured\n"
        "   Cardinal) is stored once, not once per appearance. */\n"
        f"var mlbPlayers = {js_literal(players)};\n\n"
        "/* gamePk -> array of that game's participants (both teams,\n"
        "   batters + pitchers), id+team+position only -- full per-player stat lines\n"
        "   are intentionally not stored here to keep this file's size\n"
        "   sane. Look up mlbPlayers[id] for the name. */\n"
        f"var mlbGamePlayers = {js_literal(game_players)};\n"
    )
    with open(os.path.join(DATA_DIR, 'games-players.js'), 'w') as f:
        f.write(players_js)

    print(f"Wrote games.js ({len(lean)} games), games-detail.js, games-players.js "
          f"({len(players)} unique players, {sum(len(v) for v in game_players.values())} appearances)")

    # ---- sanity: flag any game venue missing from venues.js ----
    venues_path = os.path.join(DATA_DIR, 'venues.js')
    if os.path.exists(venues_path):
        with open(venues_path) as f:
            content = f.read()
        missing = sorted({g['venue'] for g in games if f'"{g["venue"]}"' not in content})
        if missing:
            print("\nWARNING -- venues.js is missing lat/lng for:")
            for v in missing:
                print(f"  {v!r}")


if __name__ == '__main__':
    main()
